name: xelwelhr
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  connectivity_plus: ^5.0.2 
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  permission_handler: ^12.0.0+1
  location: ^8.0.0
  http: ^1.4.0
  file_picker: ^10.1.9
  url_launcher: ^6.3.0
  dropdown_search: ^5.0.6

  nepali_date_picker: 7.0.1
  flutter_secure_storage: ^9.0.0
  get: ^4.7.2
  pull_to_refresh_flutter3: ^2.0.2
  image_picker: ^1.1.2
  webview_flutter: ^4.4.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/xelwel logo1.png
    - assets/gwt logo.jpg
    - assets/medibiz logo.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/xelwelhr.png"
  min_sdk_android: 21
  remove_alpha_ios: true

